spring:
  datasource:
    url: jdbc:postgresql://c7u1tn6bvvsodf.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/dbj9ocrt4mvbfj
    username: u695s0atmefjmn
    password: pa1ba9195a9d00c7e33ec3236d8c3fb587f66c3801d03fbd61db9e54e5f1372b3
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    generate-ddl: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8080
  error:
    include-message: always
security:
    secret-key: "c11a7a92006ae9322bf336606a7311846c5847f2d5556f43952eea886f4d5655"
